import React, { useState } from 'react';
import { 
  AlertTriangle, 
  AlertCircle, 
  Search, 
  Clock, 
  ArrowRight,
  CheckCircle2
} from 'lucide-react';
import type { AlertItem, UserRole } from '../types';

interface AlertsViewProps {
  alerts: AlertItem[];
  role: UserRole;
  onSelectAlert: (alert: AlertItem) => void;
  onUpdateAlertStatus: (alertId: string, newStatus: 'New' | 'Under Review' | 'Mitigated') => void;
}

export const AlertsView: React.FC<AlertsViewProps> = ({
  alerts,
  onSelectAlert,
  onUpdateAlertStatus
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('All');
  const [levelFilter, setLevelFilter] = useState<string>('All');

  const filteredAlerts = alerts.filter(a => {
    const matchesSearch = a.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          a.unit.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          a.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'All' || a.status === statusFilter;
    const matchesLevel = levelFilter === 'All' || a.level === levelFilter;
    return matchesSearch && matchesStatus && matchesLevel;
  });

  return (
    <div className="p-8 space-y-6 max-w-7xl w-full mx-auto">
      {/* Header Controls */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-2xs space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-rose-500" />
              <h2 className="text-base font-bold text-slate-900">Welfare Alerts & Early Intervention Log</h2>
            </div>
            <p className="text-xs text-slate-500 mt-1">
              Active operational alerts generated by automated fatigue metrics and welfare officer reports
            </p>
          </div>

          <div className="flex items-center gap-3">
            {/* Search */}
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
              <input
                type="text"
                placeholder="Search alerts or unit..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-8 pr-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 w-56"
              />
            </div>
          </div>
        </div>

        {/* Filters bar */}
        <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-slate-100 text-xs">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-500 text-[11px] uppercase tracking-wider">Status:</span>
            {['All', 'New', 'Under Review', 'Mitigated'].map(st => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`px-3 py-1 rounded-lg font-semibold transition-all ${
                  statusFilter === st ? 'bg-blue-600 text-white shadow-2xs' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                {st}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-500 text-[11px] uppercase tracking-wider">Severity:</span>
            {['All', 'High', 'Moderate', 'Low'].map(lv => (
              <button
                key={lv}
                onClick={() => setLevelFilter(lv)}
                className={`px-3 py-1 rounded-lg font-semibold transition-all ${
                  levelFilter === lv ? 'bg-slate-900 text-white shadow-2xs' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                {lv}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Alert Feed List */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="bg-white rounded-2xl p-12 text-center border border-slate-200 text-slate-500 text-xs">
            No alerts found matching your criteria.
          </div>
        ) : (
          filteredAlerts.map(alert => (
            <div
              key={alert.id}
              className="bg-white rounded-2xl border border-slate-200/80 p-5 shadow-xs hover:shadow-md hover:border-blue-300 transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 group"
            >
              <div className="flex items-start gap-4 flex-1">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 mt-0.5 ${
                  alert.level === 'High' ? 'bg-rose-100 text-rose-600' :
                  alert.level === 'Moderate' ? 'bg-amber-100 text-amber-600' : 'bg-emerald-100 text-emerald-600'
                }`}>
                  {alert.level === 'High' ? <AlertTriangle className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}
                </div>

                <div className="space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="font-bold text-slate-900 text-sm group-hover:text-blue-600 transition-colors">
                      {alert.title}
                    </h3>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                      alert.level === 'High' ? 'bg-rose-100 text-rose-700' :
                      alert.level === 'Moderate' ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'
                    }`}>
                      {alert.level} Risk
                    </span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                      alert.status === 'New' ? 'bg-blue-100 text-blue-800 animate-pulse-subtle' :
                      alert.status === 'Under Review' ? 'bg-purple-100 text-purple-800' : 'bg-slate-100 text-slate-700'
                    }`}>
                      {alert.status}
                    </span>
                  </div>

                  <p className="text-xs text-slate-600 leading-relaxed max-w-2xl">
                    {alert.description}
                  </p>

                  <div className="flex flex-wrap items-center gap-4 text-[11px] text-slate-400 pt-1 font-medium">
                    <span className="text-slate-700 font-bold">Unit: {alert.unit}</span>
                    <span>•</span>
                    <span>Primary Factor: <strong className="text-slate-600">{alert.primaryFactor}</strong></span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3 text-slate-400" /> {alert.time} ({alert.date})
                    </span>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0 border-t md:border-t-0 pt-3 md:pt-0 border-slate-100">
                {alert.status !== 'Mitigated' && (
                  <button
                    onClick={() => onUpdateAlertStatus(alert.id, 'Mitigated')}
                    className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200 font-semibold rounded-xl text-xs flex items-center gap-1 transition-colors"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    Mark Mitigated
                  </button>
                )}

                <button
                  onClick={() => onSelectAlert(alert)}
                  className="px-3.5 py-1.5 bg-slate-900 hover:bg-blue-600 text-white font-semibold rounded-xl text-xs flex items-center gap-1.5 shadow-xs transition-colors"
                >
                  View Details & Action
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))
        )}
      </div>

    </div>
  );
};
